name: .NET

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: check msbuild
      run: |
        C:
        cd C:\Microsoft.NET\Framework\v4.0.30319
        dir
        msbuild
